facebookbot/views.py
#!/usr/bin/env python
from datetime import datetime
from flask import (render_template, request, redirect, url_for, Blueprint,
                   jsonify)
from pyparsing import ParseException
from requests import get
from pprint import pprint
from .models import TwitterBotModel, create_bot_hash, BotType
from .utils.rule_parser import SimpleParser
from .utils.error_handler import InvalidUsage
from .utils.db_helpers import (
    add_bot, save_rule_to_db, delete_rule_from_db, get_records_stats,
    save_defaultsettings, update_botsettings, get_defaultsettings, get_tokens,
    get_statistics, export_bots, export_users, export_tweets, export_rules,
    get_rules_with_id)
from .bot.twitter_bot import make_bot, get_user

bot = Blueprint('bot', __name__)

# dictionary where all active bots are stored. The dictionary keys are
# the ids of the bots
global active_bots
active_bots = {}


@bot.errorhandler(InvalidUsage)
def handle_invalid_usage(error):
    """
    generic error handler is called whenever InvalidUsage
    is instantiated.
    returns an error message
    """
    response = jsonify(error.to_dict())
    response.status_code = error.status_code
    return response


# home = bot.route('/', home) <- this is what the decorator means
@bot.route('/')
def home():
    """
    This function is called when localhost:5000 is opened in the browser
    """
    all_bots = TwitterBotModel.select().where(TwitterBotModel.visible == 1)
    bots_w_status = []
    for bot in all_bots:
        stats = get_statistics(bot.id)
        bot_row = {
            'bot_name': bot.bot_name,
            'follower': stats['followers'],
            'following': stats['follows'],
            'bot_hash': bot.bot_hash
        }
        if bot.id in active_bots.keys():
            bot_row['status'] = 'active'
        else:
            bot_row['status'] = 'inactive'

        bots_w_status.append(bot_row)

    bot_classes = [x.bot_class for x in BotType.select()]

    return render_template(
        'home/home.html',
        all_bots=all_bots,
        bot_classes=bot_classes,
        bots_w_status=bots_w_status)


@bot.route('/save_rule/', methods=['POST'])
def save_rule():
    """
    this function is called by a function in static/dyntable.js and
    saves a rule which is passed as json
    """
    simple_parser = SimpleParser()
    data = request.get_json()
    rule = data['rule']
    try:
        rule_dict = simple_parser.parse(rule)
        rule_dict['rule'] = rule
        rule_id = save_rule_to_db(data['bot_id'], rule_dict)
    except ParseException:
        # on parse error return json with error message
        raise InvalidUsage('rule is in wrong format', status_code=400)
    # on parse success return success message
    return jsonify({
        'message': 'rule successfully added',
        'rule_id': rule_id  # needed to add rule_id as name attribute of rule
    }), 200


@bot.route('/delete_rule/', methods=['POST'])
def delete_rule():
    """
    this function is called by a function in static/dyntable.js and
    deletes a rule which is passed as json"""
    data = request.get_json()
    try:
        delete_rule_from_db(data['bot_id'], data['rule_id'])
        return jsonify({'message': 'rule successfully deleted'}), 200
    except Exception as e:
        return jsonify({'message': 'rule could not be deleted'}), 400


@bot.route('/start_bot/', methods=['POST'])
def start_bot():
    """
    This function is called when the user presses the start button
    on the bot page. It is called by a function in static/bot_ctrl_func.js
    """
    data = request.get_json()
    bot_id = data['bot_id']
    bot = TwitterBotModel.get_by_id(bot_id)
    query = BotType.get(BotType.id == bot.type_ref)

    bot_ref = [query.import_name, query.bot_class]
    try:
        active_bots[bot_id] = make_bot(get_tokens(bot_id), bot_ref, bot_id)
        active_bots[bot_id].start()
    except Exception as e:
        return jsonify({'message': e.args}), 200
    return jsonify({'message': 'bot started'}), 200


@bot.route('/stop_bot/', methods=['POST'])
def stop_bot():
    """
    This function is called when the user presses the stop button
    on the bot page. It is called by a function in static/bot_ctrl_func.js
    """
    data = request.get_json()
    bot_id = data['bot_id']
    if bot_id in active_bots:
        abot = active_bots[bot_id]
        abot.stop()
        active_bots.pop(bot_id, None)
    return jsonify({'message': 'bot stopped'}), 200


@bot.route('/bot/<bot_hash>/', methods=['GET', 'POST'])
def show_bot(bot_hash):
    """
    this function is called when the user select a bot in the sidebar and
    shows the information of a specific bot
    """
    bot_obj = TwitterBotModel.get(TwitterBotModel.bot_hash == bot_hash)
    all_bots = (TwitterBotModel.select().where(TwitterBotModel.visible == 1))
    # ^ dictionary
    bot_classes = [x.bot_class for x in BotType.select()]
    active = False
    if bot_obj.id in active_bots:
        active = True

    follower_count = get_records_stats(bot_obj.id, "follower", 8)
    retweet_count = get_records_stats(bot_obj.id, "retweeted", 8)
    received_count = get_records_stats(bot_obj.id, "mentions", 8)
    tweet_count = get_records_stats(bot_obj.id, "tweets", 8)

    srt_received_count = [
        value for (key, value) in sorted(received_count.items(), reverse=True)
    ]
    srt_follower_count = [
        value for (key, value) in sorted(follower_count.items(), reverse=True)
    ]
    srt_retweet_count = [
        value for (key, value) in sorted(retweet_count.items(), reverse=True)
    ]
    srt_tweet_count = [
        value for (key, value) in sorted(tweet_count.items(), reverse=True)
    ]

    current_bot = {
        'bot_id': bot_obj.id,
        'bot_name': bot_obj.bot_name,
        'active': active,
        'bot_hash': bot_obj.bot_hash,
        'user_name': bot_obj.user_name,
        'follower_count': srt_follower_count,
        'retweet_count': srt_retweet_count,
        'received_count': srt_received_count,
        'tweet_count': srt_tweet_count
    }

    # pprint(current_bot)
    return render_template(
        'twitterbot/twitterbot.html',
        all_bots=all_bots,
        current_bot=current_bot,
        bot_classes=bot_classes)


@bot.route('/bot/<bot_hash>/settings/', methods=['GET'])
def show_bot_settings(bot_hash):
    """
    This function is called when the user presses the settings button on
    a bot page and it shows the settings page for one specific bot
    """
    bot_obj = TwitterBotModel.get(TwitterBotModel.bot_hash == bot_hash)
    all_bots = (TwitterBotModel.select().where(TwitterBotModel.visible == 1))
    bot_classes = [x.bot_class for x in BotType.select()]
    active = False
    rules = get_rules_with_id(bot_obj.id)
    ruledict = {}
    for rule_id, rule in rules.items():
        ruledict[rule_id] = 'if tweet contains "{}" then "{}"'.format(
            rule[0], rule[1])

    if bot_obj.id in active_bots:
        active = True
    current_bot = {
        'id': bot_obj.id,
        'bot_name': bot_obj.bot_name,
        'active': active,
        'bot_hash': bot_hash,
        'min_resp_t': bot_obj.min_resp_t,
        'max_resp_t': bot_obj.max_resp_t,
        'routine_t': bot_obj.routine_t,
        'retweeted_sleep': bot_obj.retweeted_sleep,
        'follower_sleep': bot_obj.follower_sleep,
        'd_message_sleep': bot_obj.d_message_sleep,
    }
    default_settings = get_defaultsettings(1)
    return render_template(
        'settings/settings.html',
        current_bot=current_bot,
        all_bots=all_bots,
        rules=ruledict,
        default_settings=default_settings,
        bot_classes=bot_classes)


@bot.route('/settings/')
def show_common_settings():
    """
    this function is called when the user clicks the common settings
    button on any page and it shows the default settings which are used
    on bot creation
    """
    all_bots = (TwitterBotModel.select().where(TwitterBotModel.visible == 1))
    bot_classes = [x.bot_class for x in BotType.select()]

    default_settings = get_defaultsettings(1)
    return render_template(
        'settings/settings.html',
        all_bots=all_bots,
        default_settings=default_settings,
        bot_classes=bot_classes)


@bot.route('/delete_bot/', methods=['POST'])
def delete_bot():
    """
    this function is called when the user clicks the remove bot
    button on the bot settings page. It does not delete the
    but removes it from visible space.
    Due to the fact that the bot is not deleted from db its data
    will be in future exports
    """
    q = (TwitterBotModel.update({
        TwitterBotModel.visible: 0
    }).where(TwitterBotModel.id == request.form['bot_id']))
    q.execute()
    return redirect(url_for('bot.home'), code=302)


@bot.route('/create_bot/', methods=['POST'])
def create_bot():
    """
    this function is called when the user clicks the save bot button and
    creates a bot. It is called by a funcion in static/utils.js
    """
    try:
        data = request.get_json()
        query = BotType.get(BotType.bot_class == data['bot_class'])

        bot_ref = [query.import_name, query.bot_class]
        data['type_ref'] = query.id
        data['bot_hash'] = create_bot_hash(data['bot_name'])

        tokens = dict(filter(lambda i:i[0] in ['access_token_key',
                'access_token_secret','consumer_key','consumer_secret'], data.items()))

        user_dict = get_user(tokens, data['user_name'])
        bot_id = add_bot(data, user_dict)
        #to save the statistics
        make_bot(tokens, bot_ref, bot_id)
    except Exception as e:
        return jsonify({'message': e.args}), 400
    return jsonify({'message': 'Bot successfully created'}), 200


@bot.route('/ch_bot_settings/', methods=['POST'])
def change_bot_settings():
    """
    this function is called when the user clicks the save settings button
    on any settings page. If a bot_id is passed in the request

facebookbot/templates/layout.html
<!DOCTYPE html>
<html lang="de">
<head>
  {% block head %}
  <title>{% block title %}{% endblock %} - Twitter Bot</title>
  <!-- begin favicons -->
  <link rel="apple-touch-icon" sizes="180x180" href="{{ url_for('static', filename='img/favicon/apple-touch-icon.png') }}">
  <link rel="icon" type="image/png" sizes="32x32" href="{{ url_for('static', filename='img/favicon/favicon-32x32.png') }}">
  <link rel="icon" type="image/png" sizes="16x16" href="{{ url_for('static', filename='img/favicon/favicon-16x16.png') }}">
  <link rel="manifest" href="{{ url_for('static', filename='img/favicon/site.webmanifest') }}">
  <link rel="mask-icon" href="{{ url_for('static', filename='img/favicon/safari-pinned-tab.svg') }}" color="#3ab6da">
  <link rel="shortcut icon" href="{{ url_for('static', filename='img/favicon/favicon.ico') }}">
  <meta name="msapplication-TileColor" content="#2d89ef">
  <meta name="msapplication-config" content="{{ url_for('static', filename='img/favicon/browserconfig.xml') }}">
  <meta name="theme-color" content="#ffffff">
  <!-- end favicons -->
  <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">
  <script type="text/javascript" src="{{ url_for('static', filename='jquery.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='Chart.bundle.js') }}"> </script>
  <script type="text/javascript" src="{{ url_for('static', filename='utils.js') }}"> </script>
  <script type="text/javascript" src="{{ url_for('static', filename='bootstrap.min.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='sidebar.js') }}"></script>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% endblock %}
</head>

<body>
<div class="wrapper">
  <div id="sidebar" class="sidebar_visible">
    <div class="sidebar-header">
      <img src="{{ url_for('static', filename='img/twitter_logo.jpg') }}" height="42" width="42" alt="Twitter Logo">
    </div>
    <ul class="list-unstyled components">
      <!-- set active if current site is home -->
      <li {% if request.path==url_for('bot.home') %} class="active"{% endif %}><a href="{{ url_for('bot.home') }}">Home</a></li>
      {% if all_bots %}
        {% for bot in all_bots %}
      <!-- set active if current site is a bot site -->
          <li {% if  request.path == url_for('bot.show_bot', bot_hash=bot.bot_hash) %} class="active" {% endif %}><a href="{{ url_for('bot.show_bot', bot_hash=bot.bot_hash) }}">{{ bot.bot_name }}</a></li>
        {% endfor %}
      {% endif %}
    </ul>
  </div>
  <div id="content" class="col-sm-12">
    <div class="page-header col-sm-12" >
      <h1>{% block heading %}{% endblock %}</h1>
    </div>
    <div class="col-sm-12">
      <div class="row col-sm-12" id="content_top"></div>
    </div>
    <div class="row">
      <div class="col-sm-10">
        <button type="button" id="sidebarCollapse" class="btn btn-info navbar-btn" data-toggle="tooltip" title="collapse and expand the sidebar">
          Menue
        </button>
        <button type="button" id="addBot" class="btn btn-success" data-toggle="collapse" data-target="#botform" data-toggle="tooltip" title="add a new bot">
          Add Bot
        </button>
        <a href="{{ url_for('bot.show_common_settings') }}">
          <button type="button" id="refresh" class="btn btn-primary" data-toggle="tooltip" title="General settings for all bots. Except they have own settings. You can find them on the bot page by pressing 'Settings'.">
          Common Settings
          </button>
        </a>
        <button type="button" id="export" class="btn btn-warning" data-toggle="tooltip" title="export data">
          Export
        </button>
      </div>
    </div>
    <div id="botform" class="collapse form-group">
        <div class="row">
          <div class="col-sm-10">
            <span>Bottyp</span>
            <select id="bot_class" class="form-control" name="bot_class" data-style="btn-primary" id="botclass" data-toggle="tooltip" title="Select a bot type based on the files in facebookbot/bot/userbots">
              {% if bot_classes %}
                {% for bot_class in bot_classes %}
                  <option  value="{{ bot_class }}">{{ bot_class }}</option>
                {% endfor %}
              {% endif %}
            </select>
          </div>
        </div>
          <div class="row">
            <div class="col-sm-10">
              <span >Botname</span>
              <input id="bot_name" type="text" value="" data-toggle="tooltip" title="Give the bot a unique name." class="form-control" name="bot_name">
            </div>
            <div class="col-sm-10">
              <span >Username</span>
              <input data-toggle="tooltip" title="Input the twitter username, without the @ in the front, for which you created the tokens." id="user_name" type="text" value="" class="form-control" name="user_name">
            </div>
            <div class="col-sm-10">
              <span >access_token_key</span>
              <input id="access_token_key" type="text" value="" class="form-control" name="access_token_key" data-toggle="tooltip" title="Input the access_token_key for the bot. Generated via apps.twitter.com .">
            </div>
            <div class="col-sm-10">
              <span >access_token_secret</span>
              <input title="Input the access_token_secret for the bot. Generated via apps.twitter.com ." id="access_token_secret" type="text" value="" class="form-control" name="access_token_secret">
            </div>
            <div class="col-sm-10">
              <span >consumer_key</span>
              <input title="Input the cons_key for the bot. Generated via apps.twitter.com ." id="consumer_key" type="text" value="" class="form-control" name="consumer_key">
            </div>
            <div class="col-sm-10">
              <span >consumer_secret</span>
              <input title="Input the consumer_secret for the bot. Generated over apps.twitter.com ." id="consumer_secret" type="text" value="" class="form-control" name="consumer_secret">
            </div>
            <div class="row ">
              <br>
            </div>
            <div class="row col-sm-2">
              <input type="button" id="save_bot" class="btn btn-success" value="submit" title="This will add the bot to the database with the above entered values.">
            </div>
          </div>
      </form>
    </div>
    <div class="container col-sm-12" >
      <div class="row col-sm-12" id="content_top"></div>
      {% block content %} {% endblock %}
    </div>
  </div>
</div>
</body>

</html>
<!-- Template for Messagebox -->
<div class="row alert alert-dismissible hidden hidden_messagebox" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
  <strong class="message">Title</strong>
</div>